id: 66809911-775f-44ed-a5bb-dedb2649d7d7
name: Bitcoin Beach
category: communities
address_city_country: El Zonte, El Salvador
address_line_2: null
address_line_3: null
language:
  - fr
  - de
links:
  twitter: twitter.com
  youtube: youtube.com
  github: ""
original_language: fr
proofreading:
  - language: en
    last_contribution_date: 2024-08-31T00:00:00.000Z
    urgency: 1
    contributor_names:
      - Asi0Flammeus
    reward: 0.07
  - language: cs
    last_contribution_date: null
    urgency: 1
    contributor_names: null
    reward: 0.19
  - language: de
    last_contribution_date: null
    urgency: 1
    contributor_names: null
    reward: 0.14
  - language: es
    last_contribution_date: null
    urgency: 1
    contributor_names: null
    reward: 0.17
  - language: et
    last_contribution_date: null
    urgency: 1
    contributor_names: null
    reward: 0.19
  - language: fi
    last_contribution_date: null
    urgency: 1
    contributor_names: null
    reward: 0.19
  - language: fr
    last_contribution_date: null
    urgency: 1
    contributor_names: null
    reward: 0.14
  - language: id
    last_contribution_date: null
    urgency: 1
    contributor_names: null
    reward: 0.21
  - language: it
    last_contribution_date: null
    urgency: 1
    contributor_names: null
    reward: 0.17
  - language: ja
    last_contribution_date: null
    urgency: 1
    contributor_names: null
    reward: 0.23
  - language: nb-NO
    last_contribution_date: null
    urgency: 1
    contributor_names: null
    reward: 0.19
  - language: pt
    last_contribution_date: null
    urgency: 1
    contributor_names: null
    reward: 0.14
  - language: ru
    last_contribution_date: null
    urgency: 1
    contributor_names: null
    reward: 0.19
  - language: vi
    last_contribution_date: null
    urgency: 1
    contributor_names: null
    reward: 0.23
  - language: zh-Hans
    last_contribution_date: null
    urgency: 1
    contributor_names: null
    reward: 0.21
tags:
  - tags
  - for
  - testing
contributor_names:
  - Rogzy-DB
