id: 66809911-775f-44ed-a5bb-dedb2649d7d7
name: Bitcoin Beach
language:
  - fr
  - de
links:
  twitter: twitter.com
  youtube: youtube.com
  github: ""
category: communities
original_language: fr
tags:
  - tags
  - for
  - testing
contributor_names:
  - Rogzy-DB
